# Generated by Django 5.1.2 on 2024-11-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_score',
            field=models.IntegerField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
