# Generated by Django 5.1.2 on 2024-11-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_score',
            field=models.IntegerField(),
        ),
    ]
