# Generated by Django 5.1.3 on 2024-12-09 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='picture',
            field=models.ImageField(default='temp', upload_to='pictures/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='house_trade.seller'),
        ),
    ]
