# Generated by Django 5.1.3 on 2024-12-10 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_trade', '0002_house_picture_house_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='description',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='photo',
            field=models.ImageField(default='hi', upload_to='photoes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='house_trade.buyer'),
        ),
    ]
